### ISSUE TITLE
服务器连不上数据库

### ISSUE THREAD

**Issue by FatDong1** [page-pipepline/pipeline-editor#3]
```
PS F:\code\front-end-service\pipeline\pipeline-node-server> npm run dev

> pipeline-node-server@0.2.0 dev F:\code\front-end-service\pipeline\pipeline-node-server
> egg-bin dev

2019-04-13 20:43:08,230 INFO 10184 [master] node version v8.9.0
2019-04-13 20:43:08,233 INFO 10184 [master] egg version 2.21.1
2019-04-13 20:43:10,381 INFO 10184 [master] agent_worker#1:15808 started (2144ms)
2019-04-13 20:43:18,631 ERROR 16228 [egg-mongoose] mongodb://mongouser:password@localhost:27017/pipeline?authSource=admin disconnected
2019-04-13 20:43:18,633 ERROR 16228 nodejs.ECONNREFUSEDError: [egg-mongoose]connect ECONNREFUSED 127.0.0.1:27017
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 27017
name: "ECONNREFUSEDError"
pid: 16228
hostname: DESKTOP-DHNRKSJ

2019-04-13 20:43:18,636 ERROR 16228 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: [egg-mongoose]connect ECONNREFUSED 127.0.0.1:27017
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 27017
name: "ECONNREFUSEDError"
pid: 16228
hostname: DESKTOP-DHNRKSJ

2019-04-13 20:43:18,637 ERROR 16228 nodejs.ECONNREFUSEDError: [egg-mongoose]connect ECONNREFUSED 127.0.0.1:27017
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 27017
name: "ECONNREFUSEDError"
pid: 16228
hostname: DESKTOP-DHNRKSJ

2019-04-13 20:43:18,638 ERROR 16228 [app_worker] start error, exiting with code:1
[2019-04-13 20:43:18.643] [cfork:master:10184] worker:16228 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2019-04-13 20:43:18.644] [cfork:master:10184] don't fork, because worker:16228 will be kill soon
2019-04-13 20:43:18,645 INFO 10184 [master] app_worker#1:16228 disconnect, suicide: false, state: disconnected, current workers: ["1"]
2019-04-13 20:43:18,651 WARN 15808 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2019-04-13 20:43:18.662] [cfork:master:10184] worker:16228 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2019-04-13 20:43:18,664 ERROR 10184 nodejs.AppWorkerDiedError: [master] app_worker#1:16228 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (F:\code\front-end-service\pipeline\pipeline-node-server\node_modules\egg-cluster\lib\master.js:411:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (F:\code\front-end-service\pipeline\pipeline-node-server\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (F:\code\front-end-service\pipeline\pipeline-node-server\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.cluster.on (F:\code\front-end-service\pipeline\pipeline-node-server\node_modules\egg-cluster\lib\master.js:280:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 10184
hostname: DESKTOP-DHNRKSJ

2019-04-13 20:43:18,666 ERROR 10184 [master] app_worker#1:16228 start fail, exiting with code:1
2019-04-13 20:43:18,667 ERROR 10184 [master] exit with code:1
⚠️  Error: F:\code\front-end-service\pipeline\pipeline-node-server\node_modules\egg-bin\lib\start-cluster {"workers":1,"baseDir":"F:\\code\\front-end-serv
ice\\pipeline\\pipeline-node-server","framework":"F:\\code\\front-end-service\\pipeline\\pipeline-node-server\\node_modules\\egg"} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pipeline-node-server@0.2.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pipeline-node-server@0.2.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xuhao\AppData\Roaming\npm-cache\_logs\2019-04-13T12_43_18_710Z-debug.log
```

**Comment by FatDong1** [comment]
改了一下后端代码连接数据库的host就可以了

**Comment by whitellily** [comment]
> 改了一下后端代码连接数据库的host就可以了

具体怎样修改的呀，遇到同样问题了
